// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Path = require("path");
var Caml_splice_call = require("bs-platform/lib/js/caml_splice_call.js");

function dirname(prim) {
  return Path.dirname(prim);
}

function extname(prim) {
  return Path.extname(prim);
}

function normalize(prim) {
  return Path.normalize(prim);
}

function resolve(prim) {
  return Caml_splice_call.spliceApply(Path.resolve, [prim]);
}

exports.dirname = dirname;
exports.extname = extname;
exports.normalize = normalize;
exports.resolve = resolve;
/* path Not a pure module */
